### ISSUE TITLE
No module named 'uplink'

### ISSUE THREAD

**Issue by stefxx** [tinkerborg/thinq2-python#1]
HI, thanks for your great work. However, I get an error when running the example:

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from thinq2.controller.auth import ThinQAuth
  File "thinq2-python\thinq2\controller\auth.py", line 9, in <module>
    from uplink.clients.io import RequestTemplate, transitions
ModuleNotFoundError: No module named 'uplink'

**Comment by stefxx** [comment]
Never mind. I should learn to read first.

**Comment by phuongpham** [comment]
I also get the same error. I have tried to read readme but didn't find some solution.
What did you do? @stefxx
